// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/avatar/{id}": {
            "get": {
                "description": "Gets Avatar for CONTACT, Group or Avatar by ID",
                "produces": [
                    "image/png"
                ],
                "summary": "Avatar Endpoint",
                "parameters": [
                    {
                        "enum": [
                            "CONTACT",
                            "GROUP",
                            "AVATAR"
                        ],
                        "type": "string",
                        "description": "CONTACT, GROUP or AVATAR",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Image",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/groups": {
            "get": {
                "description": "Einfacher Test",
                "produces": [
                    "text/plain"
                ],
                "summary": "Test Endpoint",
                "responses": {
                    "200": {
                        "description": "Test OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "Einfacher Test",
                "produces": [
                    "text/plain"
                ],
                "summary": "Test Endpoint",
                "responses": {
                    "200": {
                        "description": "Test OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BFF API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
