/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsGroupMember } from './ModelsGroupMember';
import {
    ModelsGroupMemberFromJSON,
    ModelsGroupMemberFromJSONTyped,
    ModelsGroupMemberToJSON,
    ModelsGroupMemberToJSONTyped,
} from './ModelsGroupMember';

/**
 * 
 * @export
 * @interface ModelsGroup
 */
export interface ModelsGroup {
    /**
     * 
     * @type {boolean}
     * @memberof ModelsGroup
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsGroup
     */
    creator?: string;
    /**
     * 
     * @type {Array<ModelsGroupMember>}
     * @memberof ModelsGroup
     */
    groupMember?: Array<ModelsGroupMember>;
    /**
     * 
     * @type {string}
     * @memberof ModelsGroup
     */
    groupName?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGroup
     */
    groupUid?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsGroup
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsGroup
     */
    messageCount?: number;
}

/**
 * Check if a given object implements the ModelsGroup interface.
 */
export function instanceOfModelsGroup(value: object): value is ModelsGroup {
    return true;
}

export function ModelsGroupFromJSON(json: any): ModelsGroup {
    return ModelsGroupFromJSONTyped(json, false);
}

export function ModelsGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'archived': json['archived'] == null ? undefined : json['archived'],
        'creator': json['creator'] == null ? undefined : json['creator'],
        'groupMember': json['group_member'] == null ? undefined : ((json['group_member'] as Array<any>).map(ModelsGroupMemberFromJSON)),
        'groupName': json['group_name'] == null ? undefined : json['group_name'],
        'groupUid': json['group_uid'] == null ? undefined : json['group_uid'],
        'id': json['id'] == null ? undefined : json['id'],
        'messageCount': json['message_count'] == null ? undefined : json['message_count'],
    };
}

export function ModelsGroupToJSON(json: any): ModelsGroup {
    return ModelsGroupToJSONTyped(json, false);
}

export function ModelsGroupToJSONTyped(value?: ModelsGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived': value['archived'],
        'creator': value['creator'],
        'group_member': value['groupMember'] == null ? undefined : ((value['groupMember'] as Array<any>).map(ModelsGroupMemberToJSON)),
        'group_name': value['groupName'],
        'group_uid': value['groupUid'],
        'id': value['id'],
        'message_count': value['messageCount'],
    };
}

